import Head from 'next/head';
import Image from 'next/image';
import Blog from '../components/blog';
import Contact from '../components/contact';
import Designer from '../components/designer';
import Footer from '../components/footer';
import Gallery from '../components/gallery';
import Header from '../components/header';
import Navbar from '../components/navbar';
import Projects from '../components/projects';
import Stats from '../components/stats';
import Testimonials from '../components/testimonials';

export default function Home() {
	return (
		<div>
			<Head>
				<title>NOHA ALI DESIGNS</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Navbar />
			 <Header />
			{/*<Gallery /> */}
		<main>
		
		<Projects />
		<Testimonials />
		<Blog />
		<Designer />
		<Contact />
		</main>
		<Footer />
		</div>
	);
}
  